version: '3.8'

services:
  frontend_api:
    build:
      context: .
      dockerfile: customer_api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: frontend_db
      DB_USER: frontend_user
      DB_PASSWORD: frontend_password
      PORT: 8000

  backend_api:
    build:
      context: .
      dockerfile: admin_api/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: backend_db
      DB_USER: backend_user
      DB_PASSWORD: backend_password
      PORT: 8001

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
